services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - sist_net
    restart: always
  nginx:
    image: nginx:alpine
    networks:
      - sist_net
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - frontend

networks:
  sist_net:
    driver: bridge
    external: true # 외부 네트워크 사용
